### ISSUE TITLE
Majora's Mask tunic color option doesn't work!

### ISSUE THREAD

**Issue by GamePerson** [Admentus64/Patcher64Plus-Tool#10]
Hey all!
I'm sorry if this isn't a very good bug report, but I want to help this project, even if it's a small contribution.

In MM, everything works correctly. That is, I have the options and redux enabled and adjusted to my liking. The only thing I have tested that doesn't work is the Kokiri Tunic option in the colors tab.

I hope this is descriptive enough. Glad to help.

**Comment by Admentus64** [comment]
The "Kokori Tunic Color" option is supposed to be disabled (and not useable thus) if the "Improved Link Model" option is checked. The color option is not compatible with the new model due to changes in the model's file. There's nothing planned to address this for now.

However, the "Kokori Tunic Color" option should work on the vanilla model. Should this not work, please notify me and I fix it.

**Comment by Admentus64** [comment]
Fixed with v11.1.2
https://github.com/Admentus64/Patcher64Plus-Tool/releases/tag/v11.1.2

**Comment by GamePerson** [comment]
Just wondering, is this option also supposed to change the tunic color for Link's other forms? Because I've tested the new version and Hylian Link's tunic color is changed but is still the default green color when in Deku, Goron, or Zora form.

**Comment by Admentus64** [comment]
No. The Tunic Color option only affects Hylian Link. This tunic is in grayscale and the game assigns a color for it ingame. It's pretty easy to change, as it's just a few hex color to change. As a result you don't need different HD textures either for each color.

The transformation mask forms (Deku, Goron, Zora) work differently. Instead of editing that color assignment code, the textures used for these forms are in green already and not in grayscale. Thus the game does not assign a color. Editing the colors for these forms is much more complicated and you essentially end up changing the textures themselves. This also causes unique texture dumps for HD support.

You can use the "Recolor Mask Forms" option instead, which recolors Goron Link into red and Zora Link into blue. It should have HD textures with the upcoming Zelda 64 UHD v5.1 texture pack update for Dolphin as well.
