### ISSUE TITLE
Virus detected in Win10

### ISSUE THREAD

**Issue by manuelx98** [Admentus64/Patcher64Plus-Tool#11]
Hi there, sorry for my ignorance, I didn't find any post about this and I got a little worried. When I download the latest archive and extract it Windows 10 detects a virus in `Patcher64+ Tool.exe`, saying it is a potential `Trojan:Script/Wacatac.B!ml`, maybe it's because it uses PowerShell to work? Can you confirm there aren't any viruses in this? Thank you.

**Comment by Admentus64** [comment]
The `Patcher64+ Tool.exe` is nothing more than a compiled version of the main `Patcher64+ Tool.ps1` script. Windows Defender can be pretty over-sensitive at times. If you feel at unease to use the compiled .exe then running the .ps1 script essentially does the same.

The issue probably happens because PowerShell does make some use of certain command, mostly locating files within the Patcher64+ folder itself and the path the ROM is located and should be patched into.

**Comment by OutRunner** [comment]
I actually get this as well but I’m using the uncompiled version so I can see it’s ucon64.exe that Windows Defender doesn’t like rather than anything in the main patching tool.

**Comment by Admentus64** [comment]
ucon has been gone for quite some time now. Same issue. If you update Patcher64+ you should see ucon is gone.

**Comment by OutRunner** [comment]
Ah good to know I can delete it. I downloaded a separate copy of ucon a while back after Defender “helpfully” removed it which is why it’s still hanging around the directory even though the latest versions aren’t using it.

**Comment by Admentus64** [comment]
ucon was mostly used in order to convert .n64 ROM to .z64. In order avoid avoid scanners going haywire on this, I ended up removing ucon and instead implement it's conversion technique manually through PowerShell code.
