### ISSUE TITLE
[BUG] Unable to trade odd potion for poachers saw

### ISSUE THREAD

**Issue by Tyler-Fox** [Admentus64/Patcher64Plus-Tool#126]
**Description**
Attempting to trade the odd potion with fado results in the prompt for "yes" or "no" not appearing

**How to Reproduce**
Uncertain, I thought it was because i enabled the poachers saw fix but disabling it did not fix the issue. 

**Expected behavior**
The options for yes and no should appear

**Screenshots**
Attached is a screenshot
![20240123_025313 1](https://github.com/Admentus64/Patcher64Plus-Tool/assets/154476969/baa0da89-206b-4066-9828-3968eb7d619c)

**Log files**
Log file added
[2024-01-23.log](https://github.com/Admentus64/Patcher64Plus-Tool/files/14021139/2024-01-23.log)

**Comment by Admentus64** [comment]
Will confirm later.

**Comment by GoldenMariaNova** [comment]
> snips

Nah. I found the problem right away : The **Message ID 10B8** lack this at the end : 
"**_(Two Choices) (G)Yes
No(W)_**" (The Parentheses represents arrows  **< >**, otherwise this post screw itself.)

Since **Line 2249** of **Ocarina of Time.psm1** replaces the entire dialogue, it should have been added at the very end.

**Comment by Admentus64** [comment]
I see. Thank you for confirming.

I already had a suspicion it was a broken textbox edit.

**Comment by Tyler-Fox** [comment]
Does this mean it was my fault? Did some parameter i changed cause this?

**Comment by GoldenMariaNova** [comment]
> snips

Lol No. Not at all. It's a "I forgor" moment on the side of the patcher, should be fixed soon.

**Comment by Admentus64** [comment]
Fixed
