### ISSUE TITLE
Building from source

### ISSUE THREAD

**Issue by kimimaru4000** [Admentus64/Patcher64Plus-Tool#14]
How can I build this tool from the source code and what dependencies do I need? I'm not on Windows.

**Comment by Admentus64** [comment]
There's no need to build the tool. At least not on Windows. It's coded in PowerShell. And the code is simply executed by running the .ps1 script. Windows 10 comes natively with it installed. On Windows 7/8 you will need to install PowerShell separately.

As for those who use Linux or Mac. I honestly have no idea. You're probably out of luck. You should try if you can install PowerShell on those platforms, but it probably won't do much good since the tool is heavily based on it's use of `System.Windows.Forms` for it's GUI design which probably is Windows exclusive.
