### ISSUE TITLE
"Failed! Could not find file." while trying to patch OoT to Redux with custom options.

### ISSUE THREAD

**Issue by HugeTaffer** [Admentus64/Patcher64Plus-Tool#16]
![Patcher64+ Tool 23_03_2021 19_55_40](https://user-images.githubusercontent.com/78643072/112202974-eafd5f80-8c09-11eb-949f-37324b141cd6.png)

I am confused as to how to input customized settings into OoT Redux. Redux by itself works fine, but I want to enable some settings that's located in the patch options category such as 3x speed text and skipping some cutscenes. But if I click "Patch Selected Option", after enabling some settings in the program, the program would crash with the error message "Failed! Could not find file."

I would appreciate any pointers as to how to make it all work :)

**Comment by HugeTaffer** [comment]
It did actually finish doing his thing after a while but apparently with some errors, should I expect any issues?

**Comment by HugeTaffer** [comment]
![RetroArch Mupen64Plus-Next 2 2-Vulkan a6a6bfd 23_03_2021 21_19_44](https://user-images.githubusercontent.com/78643072/112213028-9233c400-8c15-11eb-9394-cc2026fece8d.png)

Yup, here's one issue :(

This doesn't happen on default Redux hack. I feel like I'm doing something terribly wrong.

**Comment by HugeTaffer** [comment]
Running the .ps1 file with windows powershell did the trick.

**Comment by Admentus64** [comment]
Riiiiight...

Start by sharing the log file first. But it seems you closed the issue, so it's seem like it's fine already? I guess?

Also, there's no need to include the BPS patch for Redux. Patcher64+ already does it when the "Enable Redux" checkbox is checked.

If there is a conflicting issues, start by disabling all options, and then enabling options one by one until you know which one option is causing the potential "conflict". Easiest way to do so would be to use the Divide and Conquer tactic (https://en.wikipedia.org/wiki/Divide-and-conquer_algorithm), aka enable half of the options, check for issues, if not enable half of the remaining options, otherwise remove half of the enabled options, rinse and repeat until you get the definitive "broken" option.
