### ISSUE TITLE
Not patching correctly.

### ISSUE THREAD

**Issue by Lombardi128** [Admentus64/Patcher64Plus-Tool#18]
After selecting all my options and patching, I cannot get it to run properly in anything. Wii VC Wad injection causes the app to appear as unknown, Project64 crashes when trying to load the rom, and when injecting into Wii U VC all the characters and buildings are invisible. Are there any dependencies this requires besides PowerShell, or are there any options that are incompatible with each other?

**Comment by Admentus64** [comment]
Please post your log file first.

**Comment by Lombardi128** [comment]
Here's the one from today. I tried patching the rom several times, changing a few options to see if it would work. I also tested the standalone OC Redux patch from Romhacking.net, and the problems still occurred. Could the Redux patch be interfering with any of the custom options?
[2021-04-17-15-45-34.log](https://github.com/Admentus64/Patcher64Plus-Tool/files/6330120/2021-04-17-15-45-34.log)

**Comment by Admentus64** [comment]
Don't use the Redux patch from Romhacking.net. The Redux patch used within Patcher64+ is a customized to work a bit more modular.

However, if you don't seem to be able to run Ocarina of Time Redux or Majora's Mask on any emulator, including Project64, when you manually patched it, then there are other issues at play. Make sure that the patched ROM uses the 8MB Expansion Pak in Project64. Both Redux patched Zelda ROMs require the 8MB Expansion Pak.

I seemed to have noticed you drag and dropped the "Ocarina of Time Redux.bps" into the text bar as well. There's no need for this. As the text bar says it's meant for "CUSTOM" patches, aka, those Patcher64+ doesn't include. Redux is already included in Patcher64+, so just use the "Enable Redux" checkbox instead. Pressing the larger Patch button won't apply that Custom patch anyway, which is only applied when using the Apply Patch button right next besides it.

According to the log, no actual errors were found.

If you suspect it's a specific incompatible option you would need to isolate it's cause. Please make use of bisecting.

How to do so:
- Patch the ROM with the options you have. If the ROM works. You are good to go. If not...
- Patch the ROM again with the minimum amount of options possible. If it still not works, then there is a critical flaw somewhere.
- Great, if it does work, then it means some option inbetween caused a conflict. Patch again by enabling half of the options you previously had.
- If that still worked, enable half of the rest you left and repeat. Otherwise disable half of what you currently use. Repeat this cycle over and over until you can narrow it down to a single option.

**Comment by Admentus64** [comment]
Closing this issue, since it works then.

Patcher64+ supports the 8 MB Expansion Pak for Ocarina of Time on the Wii VC. Make sure Expand Memory is checked, through patching in Redux automatically checks that box.

Don't use the Custom Path bar like I mentioned before.

Please create a new issue for the GC Scheme option, but only when you confirm the patching process and the emulator setup itself works (I can't blame the GC Scheme option being broken if it's an exterior issue). A proper log report would be helpful too.
