### ISSUE TITLE
When installed on real Wii NAND, channel only appears in Data Management as question mark

### ISSUE THREAD

**Issue by DubiousDextop** [Admentus64/Patcher64Plus-Tool#19]
**Description**
After creating a patched VC WAD for Ocarina of Time, upon installation to a real Wii the channel is missing from the Wii Menu. When checking Wii Data Management and Channels, the channel appears as a question mark with a question mark title. Patched channel opens successfully through USB Loader GX, but cannot be moved to SD card due to no appearance on real Wii Menu.

**How to Reproduce**
1. Patch Ocarina of Time WAD with Redux using any configuration
2. Move patched WAD to USB drive
3. Use WiiModLite (A homebrew app that allows for installing WAD files directly to the Wii system memory as channels) to install the patched WAD
4. Check Data Management > Channels to find question mark channel

**Expected Behavior**
I had expected for the channel to install and appear on the Wii Menu just like any legit Virtual Console channel, as this I have had success with a Super Mario 64 specific ROM hack WAD before. In addition, my expectation was to be able to move the channel to an SD card for easy storage due to the incredibly small storage space on Wii.
______
While I don't currently have access to the log file due to being on a different device, I will add it tonight.

Thank you so much for reading! I apologize if I've done something wrong, but the way I went about doing this seemed like the normal way to do it.

**Comment by Admentus64** [comment]
Hmm, interesting issue, but I sadly I won't look into this. Only issues that can be confirmed on the emulators and setups we use are looked into (latest Dolphin dev, latest dev for Project64 + GlideN64, etc).

It's expected that Wii VC emulation kinda fails to work. Since I am lacking an overview of which options you patched and how you patched it I have no idea if it's console compatible. If it is console compatible, great! If not, that sucks. That's our stance on it, kinda.

I am not entirely familiar with the homebrew app you used, so I won't look into that either.
