### ISSUE TITLE
16:9 Widescreen (Advanced) option does not work on Wii U virtual console inject. Simple proposed fix.

### ISSUE THREAD

**Issue by Lombardi128** [Admentus64/Patcher64Plus-Tool#26]
I have run into an irritating problem. The option for advanced 16:9 Widescreen as applied by this tool does not work on Wii U Virtual Console Injection. The game freezes after the N64 logo. The simplified widescreen does work, but that just seems to re-adjust the HUD elements, and is not true 16:9.

In the tool-tip, it states that the advanced widescreen is based off of the patch by gamemasterplc, with additions from Nerrel and GhostlyDark. The normal unmodified patch by gamemasterplc does work on Wii U Virtual Console Inject. However, the selectable options and redux features do not work when using this tool to patch a rom prepatched by gamemasterplc's widescreen patch.

So a proposed fix for Wii U players would be to add an option that patches the game to 16:9 using gamemastlerplc's patch, but without the additions by Nerrel and GhostlyDark. That way it will most likely work on Wii U with both true widescreen and redux features offered by the tool.

It would be very helpful if you would consider making this additional option for Wii U users.

**Comment by GhostlyDark** [comment]
Simplified Widescreen as you have noticed only adjusts certain elements of the game, in particular squishing them to counter the stretching that occurs due to the built in GLideN64 hack. It's not meant for anything else.

The Widescreen patch that we currently use originates from gamemasterplc, using 16:9 granny story backgrounds that have been made by Nerrel (part of gamemasterplc's original Widescreen patch). What I did is port all those changes to a ROM that was decompressed properly, plus some minor fixes.

The original patch from gamemasterplc will not work with the Patcher, thus being completely incompatible with Redux and any options the Patcher offers. So your idea will absolutely not work.

I am surprised to learn however that the original patch works on Wii U. If anything, I'd need to find out what causes the Wii U VC to break and maybe I can fix something. What patch file have you used that works under Wii U VC? Are you sure it is working properly?

**Comment by Admentus64** [comment]
Actually... In Wii VC mode Simplified Widescreen does patch in 16:9 along with those adjustments. It has been removed in N64 mode patching since GlideN64's Widescreen hack is more accurate.

**Comment by Lombardi128** [comment]
By "what patch file", you mean which patch am I using that makes it true widescreen on Wii U VC? That would be the "mmws.xdelta" that is from the dropbox link in the description of gamemasterplc's video showcasing it. It seemed to work properly when I injected it using regular Majora's Mask settings. I made it through the introduction sequence and made it to Clock Town with no issue. If you'd like, I could play further to see if any hiccups occur.

gamemasterplc's Video: https://www.youtube.com/watch?v=6BfS7Pl3Yiw
Patch Link: https://www.dropbox.com/s/w8118sc2zfq9sud/mmws.xdelta?dl=1&v=6BfS7Pl3Yiw

Understandably, I never expected patching the prepatched widescreen rom to work, I would assume that your tool incorporates all features in such a way so that nothing gets overwritten by any other changes. By using the tool with the "Ignore Input Checksum" options, I would assume that different patches and changes will end up overwriting each other.

That is where the idea came from. That if you incorporated the original unmodified patch that worked as an option, then you could set it so that the changes wouldn't conflict.

**Comment by Admentus64** [comment]
Ignore Input Checksum is only for checking if the Input ROM matches the No-Intro Database hashsums, so it may proceed with patching. Nothing else.

**Comment by Lombardi128** [comment]
Yes I know, I'm just giving you my lines of reasoning.

**Comment by GhostlyDark** [comment]
It is an old patch that lacks the 16:9 granny story backgrounds.
![image](https://user-images.githubusercontent.com/31742919/147988946-ba41cbd4-12b7-49c5-a497-2d7a4ca12c93.png)

This is a newer version of the patch that does have WS backgrounds. Can you try running that one in Wii U VC? It'll help to narrow things down.
[gmp_MM_usa_n64_10_nobombers.zip](https://github.com/Admentus64/Patcher64Plus-Tool/files/7804402/gmp_MM_usa_n64_10_nobombers.zip)

**Comment by Lombardi128** [comment]
The newer patch above does indeed work. I also played a little more of the older patch. I noticed that the older patch had the motion blur turned off while the newer patch still has the motion blur on. This gave me the idea to use the tool again with all of the options I had on before, but this time I disabled motion blur and flashback overlay. To my surprise, it now boots on Wii U. However, I noticed tons of graphical glitches as I went through the introduction section. Things such as the camera jerking forward when swinging a sword, Link becoming a double image when slashing at the moving shrub bushes, and weird stretched out textures when spin dashing as a Deku Scrub.

**Comment by Admentus64** [comment]
Could you test the same but use Old Redux instead? (Select Options -> Redux -> Old Redux, requires Advanced GUI mode to show up in there)

**Comment by GhostlyDark** [comment]
I actually got WS + Redux working on my Wii U perfectly fine. I did use a WIP build of the patcher and from what I can tell there are some bugs in the patching process that Admentus needs to fix in the current build before we should continue messing around with it. I'll just update this issue with new findings.

**Comment by GhostlyDark** [comment]
Using Phacox's Injector I was able to play Majora's Mask without any graphical issues in Widescreen, with and without Redux. Cutscene effects like motion blur were kept intact. Feel free to retest once v16.1.0 is live.

> Things such as the camera jerking forward when swinging a sword, Link becoming a double image when slashing at the moving shrub bushes, and weird stretched out textures when spin dashing as a Deku Scrub.

That sounds really weird to me and at no point did I come across such issues. There could be certain options that break the Wii U VC, but since you shared no log files with us, we can't further investigate.
