### ISSUE TITLE
Feature Request: Remove object too with "Mute Owls" option for OoT

### ISSUE THREAD

**Issue by GoldenMariaNova** [Admentus64/Patcher64Plus-Tool#77]
### It is not necessarily a bug, but a big annoyance:

The muting **Kaeboora** options in OOT **Patcher64+** do work, but it seems that it do not remove its model from the maps he's in though, creating slowdown in **Hyrule field** for example (There's _4_ instances of him on there alone), and some others.

And since it can't despawn normally anymore with this on, it also looks awkward, as he endlessly idling in its respective position.

Is there a possibility to unload its model aswell, well, apart from **Lake Hylia** and atop of **Death Mountain**, as he's necessary for teleporting you to certain important zones? Or it is completely impossible to do?

**Comment by Admentus64** [comment]
Part of v20.5.0 with the revamped Scene Editor rewrite as this can't be done practically otherwise. v20.5.0 supports adding and removing actors and objects on the fly during patching while also re-adjusting and accounting for any shifts.

Owls have been deactivated before by setting their parameters to 0000. The actors and objects were never removed because that requires shifting, previously not practical to achieve.

Lag couldn't be confirmed using Project64. Please make sure to set the Counter Factor to 1 if using Project64, or use a similar overclock method on other N64 emulators.

But otherwise still sounds like a solid addition (which was already worked on). The more actors and objects are removed the more space there is for replacements. OoT supports like at most 15 objects with it's 4 MB RAM.
